version: 2.1
orbs: 
  serverless-framework: circleci/serverless-framework@2.0.0
  pulumi: pulumi/pulumi@2.1.0
jobs:
  build:
    docker: 
      - image: cimg/node:16.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login:
          access-token: 'pul-f4edae887f207ef0c10d3e60ebaef119a53b8ac0'
      - pulumi/stack_init:
          stack: 'pipeline/test-pr_${CIRCLE_BUILD_NUM}'
      - pulumi/update:
          stack: 'pipeline/test-pr_${CIRCLE_BUILD_NUM}'
      - pulumi/stack_output:
          stack: 'pipeline/test-pr_${CIRCLE_BUILD_NUM}'
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: serverless deploy -v
          name: deploy
workflows:
  deploy:
    jobs:
      - deploy