version: 2.1
orbs: 
  serverless-framework: circleci/serverless-framework@2.0.0
  pulumi: pulumi/pulumi@2.1.0
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker: 
      - image: cimg/node:16.15.0
    working_directory: ~/Data-Ingestion-Project
    
    steps:
      - checkout
      - pulumi/login:
          access-token: $pulumi_access_token
      - pulumi/stack_init:
          stack: $env
          working_directory: ~/Data-Ingestion-Project/aws_infrastructure
          secrets_provider: $profile
      - pulumi/update:
          stack: $env
          working_directory: ~/Data-Ingestion-Project/aws_infrastructure
      - pulumi/stack_output:
          stack: $env
          property_name: "dev_config"
          env_var: $env
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: serverless deploy -v
          name: deploy
workflows:
  deploy:
    jobs:
      - build
      - deploy