version: 2.1
orbs: 
  serverless-framework: circleci/serverless-framework@2.0.0
  pulumi: pulumi/pulumi@2.1.0
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker: 
      - image: cimg/node:16.15.0
    working_directory: ~/Data-Ingestion-Project/aws_infrastructure
    steps:
      - checkout
      - pulumi/login:
          access-token: 'pul-f4edae887f207ef0c10d3e60ebaef119a53b8ac0'
      - run:
          command: |
              npm install
      - pulumi/stack_init:
          stack: 'dev'
      - pulumi/update:
          stack: 'dev'
      - pulumi/stack_output:
          stack: 'dev'
          property_name: "dev_config"
          env_var: "dev"
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: serverless deploy -v
          name: deploy
workflows:
  deploy:
    jobs:
      - build
      - deploy